import google.generativeai as genai
import os
# Configure the GenAI API
genai.configure(api_key=os.environ.get("GENAI_API_KEY"))
model = genai.GenerativeModel("gemini-1.5-flash", system_instruction="You are the best python developer that helps newbies!")

def generate_response(user_query: str) -> str:
    """
    Generates a response from the AI model.

    :param user_query: The input query from the user.
    :return: The response generated by the AI model.
    """
    response = model.generate_content(user_query)
    return response.text
